In [23]:
path = "/Users/thomas/PycharmProjects/MarkovsHousehold/tests/resources/appliances/load_ts.xlsx"

In [24]:
from markovs_household.utils.appliance import ApplianceCategory

device_sheets = {
    "Waschmaschine": ApplianceCategory.WASHING_MACHINE.value,
    "Trockner": ApplianceCategory.DRYER.value,
    "Geschirrspueler": ApplianceCategory.DISH_WASHER.value,
    "Elektroherd": ApplianceCategory.STOVE.value,
    "Kuehlgeraete": ApplianceCategory.FRIDGE.value,
    "Gefriergeraete": ApplianceCategory.FREEZER.value,
    "Fernseher": ApplianceCategory.TELEVISION.value,
    "Videorecorder": ApplianceCategory.VIDEO_RECORDER.value,
    "PC": ApplianceCategory.PC.value,
    "Telekommunikation": ApplianceCategory.TELECOMMUNICATION.value,
    "Beleuchtung": ApplianceCategory.LIGHTING.value,
    "Warmwasser": ApplianceCategory.WATER_HEATING.value,
    "Restlast": ApplianceCategory.OTHER_LOAD.value
}

In [25]:
reversed_sheets = {
    ApplianceCategory.WASHING_MACHINE: "Waschmaschine",
    ApplianceCategory.DRYER: "Trockner",
    ApplianceCategory.DISH_WASHER: "Spuelmaschine",
    ApplianceCategory.STOVE: "Elektroherd",
    ApplianceCategory.FRIDGE: "Kuehlgeraet",
    ApplianceCategory.FREEZER: "Gefriergeraete",
    ApplianceCategory.TELEVISION: "Fernseher",
    ApplianceCategory.VIDEO_RECORDER: "Videorecorder",
    ApplianceCategory.PC: "PC",
    ApplianceCategory.TELECOMMUNICATION: "Telekommunikation",
    ApplianceCategory.LIGHTING: "Beleuchtung",
    ApplianceCategory.WATER_HEATING: "Warmwasser"
}

In [26]:
import pandas as pd

df = pd.read_excel(path, engine="openpyxl")

In [27]:
df.head()

,Zeitschritte nach \nStartvorgang [15min],Waschmaschine,Geschirrspueler,Trockner,Elektroherd,Kuehlgeraete,Gefriergeraete,Fernseher,Videorecorder,PC,Telekommunikation,Beleuchtung,Warmwasser,Restlast
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W],Lastprofil [W]
2,1.0,100,80,2000,700,125,130,150,30,130,40,60,18000,55
3,2.0,2000,2000,2000,700,1,1,150,30,130,40,60,NaN,NaN
4,3.0,900,80,2000,700,1,1,150,30,130,40,60,NaN,NaN

In [28]:
df = df.iloc[2::].drop(columns=["Zeitschritte nach \nStartvorgang [15min]"]).reset_index(drop=True)
df

,Waschmaschine,Geschirrspueler,Trockner,Elektroherd,Kuehlgeraete,Gefriergeraete,Fernseher,Videorecorder,PC,Telekommunikation,Beleuchtung,Warmwasser,Restlast
0,100,80,2000,700,125,130,150,30,130,40,60,18000,55
1,2000,2000,2000,700,1,1,150,30,130,40,60,NaN,NaN
2,900,80,2000,700,1,1,150,30,130,40,60,NaN,NaN
3,100,80,1600,700,125,130,150,30,130,40,60,NaN,NaN
4,100,80,1300,NaN,1,1,150,30,130,40,NaN,NaN,NaN
5,300,2000,940,NaN,1,1,150,30,130,40,NaN,NaN,NaN
6,50,300,NaN,NaN,125,130,NaN,30,130,40,NaN,NaN,NaN
7,NaN,150,NaN,NaN,1,1,NaN,30,130,40,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN

In [29]:
df = df.rename(columns=device_sheets)
df

,washing_machine,dish_washer,dryer,stove,fridge,freezer,television,video_recorder,pc,telecommunication,lighting,water_heating,other_load
0,100,80,2000,700,125,130,150,30,130,40,60,18000,55
1,2000,2000,2000,700,1,1,150,30,130,40,60,NaN,NaN
2,900,80,2000,700,1,1,150,30,130,40,60,NaN,NaN
3,100,80,1600,700,125,130,150,30,130,40,60,NaN,NaN
4,100,80,1300,NaN,1,1,150,30,130,40,NaN,NaN,NaN
5,300,2000,940,NaN,1,1,150,30,130,40,NaN,NaN,NaN
6,50,300,NaN,NaN,125,130,NaN,30,130,40,NaN,NaN,NaN
7,NaN,150,NaN,NaN,1,1,NaN,30,130,40,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,125,130,NaN,NaN,NaN,40,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,40,NaN,NaN,NaN

In [30]:
df.to_csv(path.replace(".xlsx", ".csv"), index=False)

In [35]:
for idx, x in enumerate(df["dish_washer"].dropna()):
    print(f"{idx}, {x}")

0, 80
1, 2000
2, 80
3, 80
4, 80
5, 2000
6, 300
7, 150